# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1115, 840)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.mainFrame.setObjectName("mainFrame")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.mainFrame)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(5)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.upView = QtWidgets.QGraphicsView(self.mainFrame)
        self.upView.setObjectName("upView")
        self.verticalLayout_2.addWidget(self.upView)
        self.downView = QtWidgets.QGraphicsView(self.mainFrame)
        self.downView.setObjectName("downView")
        self.verticalLayout_2.addWidget(self.downView)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.mainView = GLViewWidget(self.mainFrame)
        self.mainView.setObjectName("mainView")
        self.horizontalLayout_4.addWidget(self.mainView)
        self.horizontalLayout_4.setStretch(0, 5)
        self.horizontalLayout_4.setStretch(1, 4)
        self.verticalLayout.addWidget(self.mainFrame)
        self.parameterFrame = QtWidgets.QFrame(self.centralwidget)
        self.parameterFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.parameterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.parameterFrame.setObjectName("parameterFrame")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.parameterFrame)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, -1, 20, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.upAction = QtWidgets.QLabel(self.parameterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.upAction.sizePolicy().hasHeightForWidth())
        self.upAction.setSizePolicy(sizePolicy)
        self.upAction.setMinimumSize(QtCore.QSize(5, 5))
        self.upAction.setText("")
        self.upAction.setPixmap(QtGui.QPixmap("arrow_up.png"))
        self.upAction.setScaledContents(True)
        self.upAction.setObjectName("upAction")
        self.gridLayout.addWidget(self.upAction, 0, 1, 1, 1)
        self.rightAction = QtWidgets.QLabel(self.parameterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.rightAction.sizePolicy().hasHeightForWidth())
        self.rightAction.setSizePolicy(sizePolicy)
        self.rightAction.setMinimumSize(QtCore.QSize(50, 5))
        self.rightAction.setText("")
        self.rightAction.setPixmap(QtGui.QPixmap("arrow_right.png"))
        self.rightAction.setScaledContents(True)
        self.rightAction.setObjectName("rightAction")
        self.gridLayout.addWidget(self.rightAction, 1, 2, 1, 1)
        self.leftAction = QtWidgets.QLabel(self.parameterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftAction.sizePolicy().hasHeightForWidth())
        self.leftAction.setSizePolicy(sizePolicy)
        self.leftAction.setMinimumSize(QtCore.QSize(50, 5))
        self.leftAction.setText("")
        self.leftAction.setPixmap(QtGui.QPixmap("arrow_left.png"))
        self.leftAction.setScaledContents(True)
        self.leftAction.setObjectName("leftAction")
        self.gridLayout.addWidget(self.leftAction, 1, 0, 1, 1)
        self.downAction = QtWidgets.QLabel(self.parameterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.downAction.sizePolicy().hasHeightForWidth())
        self.downAction.setSizePolicy(sizePolicy)
        self.downAction.setMinimumSize(QtCore.QSize(50, 5))
        self.downAction.setText("")
        self.downAction.setPixmap(QtGui.QPixmap("arrow_down.png"))
        self.downAction.setScaledContents(True)
        self.downAction.setObjectName("downAction")
        self.gridLayout.addWidget(self.downAction, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout.setRowStretch(0, 1)
        self.gridLayout.setRowStretch(1, 1)
        self.gridLayout.setRowStretch(2, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.connectButton = QtWidgets.QPushButton(self.parameterFrame)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.connectButton.setFont(font)
        self.connectButton.setAutoFillBackground(False)
        self.connectButton.setObjectName("connectButton")
        self.gridLayout_2.addWidget(self.connectButton, 0, 1, 1, 1)
        self.comportCombobox = QtWidgets.QComboBox(self.parameterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comportCombobox.sizePolicy().hasHeightForWidth())
        self.comportCombobox.setSizePolicy(sizePolicy)
        self.comportCombobox.setMinimumSize(QtCore.QSize(0, 25))
        self.comportCombobox.setObjectName("comportCombobox")
        self.gridLayout_2.addWidget(self.comportCombobox, 0, 0, 1, 1)
        self.stopButton = QtWidgets.QPushButton(self.parameterFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stopButton.sizePolicy().hasHeightForWidth())
        self.stopButton.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.stopButton.setFont(font)
        self.stopButton.setAutoFillBackground(False)
        self.stopButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("stop.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.stopButton.setIcon(icon)
        self.stopButton.setIconSize(QtCore.QSize(50, 50))
        self.stopButton.setCheckable(False)
        self.stopButton.setObjectName("stopButton")
        self.gridLayout_2.addWidget(self.stopButton, 1, 1, 1, 1)
        self.gridLayout_2.setColumnStretch(0, 2)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.horizontalLayout_3.setStretch(0, 20)
        self.horizontalLayout_3.setStretch(1, 1)
        self.horizontalLayout_3.setStretch(2, 4)
        self.verticalLayout.addWidget(self.parameterFrame)
        self.verticalLayout.setStretch(0, 6)
        self.verticalLayout.setStretch(1, 1)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setIconSize(QtCore.QSize(25, 25))
        self.toolBar.setFloatable(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.connectAction = QtWidgets.QAction(MainWindow)
        self.connectAction.setCheckable(True)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("connected.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.connectAction.setIcon(icon1)
        self.connectAction.setObjectName("connectAction")
        self.toolBar.addAction(self.connectAction)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.connectButton.setText(_translate("MainWindow", "connect"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.connectAction.setText(_translate("MainWindow", "连接"))
        self.connectAction.setToolTip(_translate("MainWindow", "串口连接"))

from pyqtgraph.opengl import GLViewWidget
